"""
This file is automatically generated by the autogen package.
Please edit the marked area only. Other areas will be
overwritten when autogen is rerun.
"""

from setuptools import setup

params = dict(
    name='marley',
    description='Overview',
    version='0.0.1',
    url='https://github.com/omdena/renewable.git',
    install_requires=['Fiona', 'PyDrive', 'ee', 'folium', 'fs', 'geopy', 'ipython',
                      'matplotlib', 'numpy', 'pyfs', 'rasterio', 'scikit_image', 'scipy', 'skimage', 'tqdm'],
    packages=['marley', 'marley.utils'],
    package_data={},
    include_package_data=True,
    py_modules=[],
    scripts=None)

########## EDIT BELOW THIS LINE ONLY ##########

# not needed
for x in ["scikit_image", "scipy", "skimage", "matplotlib", "ipython"]:
    params["install_requires"].remove(x)

# not imported
params["install_requires"].extend(["fs.googledrivefs", "xlrd"])

# for notebooks
params["install_requires"].extend(
    ["rasterstats", "geopandas", "fiona", "plotly"])

########## EDIT ABOVE THIS LINE ONLY ##########

setup(**params)
